name: Combine Markdown Files for AirRepsGPT

on:
  push:
    branches: [ "main" ]

jobs:
  combine-markdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Combine Markdown Files
        run: |
          find . -name "*.md" -exec cat {} + > combined.md
          echo "Combined Markdown files into combined.md"

      - name: Change markdown arrays to csv
        run : |
          cat combined.md | tr -s ' ' | sed 's/ \?| \?/;/g' | sed 's/;-\+.*-\+;//g' > tmp_combined.md && cat tmp_combined.md > combined.md && rm tmp_combined.md

      - name: Upload Combined File as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: combined-markdown.md
          path: combined.md
