name: Combine Markdown Files for AirRepsGPT

on:
  push:
    branches: [ "main" ]

jobs:
  combine-markdown:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Combine Markdown Files
        run: |
          find ./docs -name "*.md" -exec cat {} + > combined.md
          echo "Combined Markdown files into combined.md"

      - name: Change markdown arrays to jsonl
        run : |
          cat combined.md | tr -s ' ' | sed 's/ \?| \?/;/g' | sed 's/;-\+.*-\+;//' | sed 's/^;/\["/' | sed 's/;/","/g' | sed 's/,"$/\]/g' | sed ':a;N;$!ba;s/]\n\n\[/]\n[/g' > tmp_combined.md && cat tmp_combined.md > combined.md && rm tmp_combined.md

      - name: Upload Combined File as Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          retention-days: 90
          path: combined.md

